# Generated by Django 3.0.8 on 2020-08-02 17:46

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('1', '300x250px'), ('2', '468x60px'), ('3', '728x90px'), ('4', '300x600px')], max_length=1, verbose_name='Định dạng')),
                ('html_code', models.TextField()),
            ],
            options={
                'verbose_name': 'Quảng cáo',
                'verbose_name_plural': 'Quảng cáo',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, verbose_name='Tên hiển thị')),
                ('avatar', models.ImageField(blank=True, upload_to='blogs/%Y/%m', verbose_name='Ảnh đại diện')),
                ('website', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(verbose_name='Đường dẫn')),
                ('color', models.CharField(choices=[('1', 'primary'), ('2', 'secondary'), ('3', 'success'), ('4', 'danger'), ('5', 'warning'), ('6', 'info'), ('7', 'light'), ('8', 'dark')], default='8', max_length=1, verbose_name='Màu sắc')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(verbose_name='Đường dẫn')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Mô tả')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Nội dung')),
            ],
            options={
                'verbose_name': 'Trang',
                'verbose_name_plural': 'Trang',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_intro', models.CharField(blank=True, max_length=300, verbose_name='Giới thiệu ngắn')),
                ('google_code', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('github', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Cài đặt',
                'verbose_name_plural': 'Cài đặt',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(verbose_name='Đường dẫn')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Cập nhật')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Mô tả')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Nội dung')),
                ('tags', models.CharField(blank=True, help_text='Cách nhau bởi dấu ,', max_length=200, verbose_name='Thẻ')),
                ('thumbnail', models.ImageField(blank=True, help_text='525x300px', upload_to='blogs/%Y/%m', verbose_name='Ảnh bìa')),
                ('publish', models.BooleanField(default=True, verbose_name='Công khai')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.Author', verbose_name='Tác giả')),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.Category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
            },
        ),
    ]
