# Generated by Django 3.0.7 on 2020-06-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200618_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='disName',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tên hiển thị'),
        ),
    ]
