# Generated by Django 3.0.7 on 2020-06-18 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_author_disname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cats',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='blogs.Category', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='khac', verbose_name='Đường dẫn'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='Khác', max_length=200, verbose_name='Tiêu đề'),
        ),
    ]
