# Generated by Django 3.0.7 on 2020-06-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20200618_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_728x90', models.TextField(blank=True, verbose_name='728x90px')),
                ('ad_300250', models.TextField(blank=True, verbose_name='350x200px')),
                ('ad_300x600', models.TextField(blank=True, verbose_name='300x600px')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='disName',
            field=models.CharField(max_length=50, verbose_name='Tên hiển thị'),
        ),
    ]
