# Generated by Django 3.0.7 on 2020-06-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20200619_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(verbose_name='Đường dẫn')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads', models.CharField(choices=[('300x250', '300x250px'), ('468x60', '468x60px'), ('728x90', '728x90px'), ('300x600', '300x600px')], max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='disName',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cats',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='Nội dung'),
        ),
    ]
