# Generated by Django 3.0.7 on 2020-06-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20200620_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[(1, '300x250px'), (2, '468x60px'), (3, '728x90px'), (4, '300x600px')], max_length=1, verbose_name='Định dạng')),
                ('content', models.TextField(verbose_name='Code')),
                ('publish', models.BooleanField(default=False, verbose_name='Công khai')),
            ],
        ),
        migrations.RemoveField(
            model_name='setting',
            name='ads',
        ),
        migrations.AddField(
            model_name='setting',
            name='ads',
            field=models.ManyToManyField(to='blogs.Ad', verbose_name='Quảng cáo'),
        ),
    ]
