# Generated by Django 3.0.7 on 2020-06-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20200620_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='style',
            field=models.CharField(choices=[('1', '300x250px'), ('2', '468x60px'), ('3', '728x90px'), ('4', '300x600px')], max_length=1, verbose_name='Định dạng'),
        ),
    ]
