# Generated by Django 3.0.7 on 2020-06-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20200620_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Công khai'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Công khai'),
        ),
    ]
