# Generated by Django 3.0.7 on 2020-06-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20200620_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='google_adsense',
            new_name='google_code',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='google_analytics',
        ),
    ]
