# Generated by Django 3.0.7 on 2020-06-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_auto_20200620_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='publish',
        ),
        migrations.AddField(
            model_name='setting',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='github_url',
            field=models.URLField(blank=True),
        ),
    ]
