# Generated by Django 3.0.7 on 2020-06-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20200621_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='content',
        ),
        migrations.AddField(
            model_name='ad',
            name='html_code',
            field=models.TextField(default='code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.EmailField(blank=True, max_length=20),
        ),
    ]
