# Generated by Django 3.0.7 on 2020-06-21 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_auto_20200621_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Quảng cáo', 'verbose_name_plural': 'Quảng cáo'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Trang', 'verbose_name_plural': 'Trang'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Bài viết', 'verbose_name_plural': 'Bài viết'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Cài đặt', 'verbose_name_plural': 'Cài đặt'},
        ),
    ]
