# Generated by Django 3.0.7 on 2020-06-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_auto_20200621_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='facebook_url',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='github_url',
            new_name='github',
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
