# Generated by Django 3.0.7 on 2020-06-22 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_auto_20200623_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Cập nhật'),
        ),
    ]
