# Generated by Django 3.0.7 on 2020-06-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_setting_paginate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='paginate',
        ),
    ]
