# Generated by Django 3.0.8 on 2020-07-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_auto_20200706_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='ads',
        ),
    ]
