# Generated by Django 3.0.8 on 2020-07-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0030_auto_20200720_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='badge_class',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('1', 'primary'), ('2', 'secondary'), ('3', 'success'), ('4', 'danger'), ('5', 'warning'), ('6', 'info'), ('7', 'light'), ('8', 'dark')], default='8', max_length=1, verbose_name='Màu sắc'),
        ),
    ]
