# Generated by Django 3.0.8 on 2020-07-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0032_auto_20200724_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='short_intro',
            field=models.CharField(blank=True, max_length=300, verbose_name='Giới thiệu ngắn'),
        ),
    ]
