# Generated by Django 3.0.8 on 2020-08-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0033_setting_short_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
